version: '3'
services:
  backend:
    image: rust:latest
    container_name: backend
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    entrypoint: ["sh", "-c", "cargo run"]
    depends_on:
      - mysql
      - jaeger
    networks:
      - backend-network
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file:
      - ./.env
    ports:
      - '3306:3306'
    volumes:
      - mysqlDB:/var/lib/mysql
    networks:
      - backend-network
  jaeger:
    image: jaegertracing/all-in-one:1.58
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - '5778:5778'
      - '16686:16686'
      - '4317:4317'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '4318:4318'
      - '14250:14250'
      - '14268:14268'
      - '14269:14269'
      - '9411:9411'
    networks:
      - backend-network
volumes:
  mysqlDB:
  cargo-cache:
  target-cache:
networks:
  backend-network: